title: O'Neil Market Reports
description: Technical market analysis using O'Neil methodology
baseurl: "/market_reports"  # Updated to match your repository name
url: "https://hellostudentworld.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings
theme: minima
minima:
  skin: classic

# Collections
collections:
  reports:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "reports"
    values:
      layout: "report"
  - scope:
      path: "archived_reports"
      type: ""
    values:
      layout: "report"
  - scope:
      path: ""
      extname: ".md"
    values:
      layout: "report"

# Archived reports directory
include:
  - archived_reports

# URLs
permalink: /:title/

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md